# Generated by Django 5.0.2 on 2024-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(editable=False, verbose_name='Возраст'),
        ),
    ]
